### ISSUE TITLE
ValueError: max() arg is an empty sequence (while running the tangent_cft_front_end

### ISSUE THREAD

**Issue by sachinsourav** [BehroozMansouri/TangentCFT#13]
self.node_id = max(list(self.encoder_map_node.values())) + 1
ValueError: max() arg is an empty sequence

Can anyone suggest what is the resason solution will be appreciated 
Please help
Need solution ASAP

**Comment by lishuaiCN** [comment]
Hello, I met same bug and I will appreciate if you tell me how to solve this bug.
