### ISSUE TITLE
where are the 20 fomula queries in the NTCIR-12dataset？

### ISSUE THREAD

**Issue by Jehuty-ML** [BehroozMansouri/TangentCFT#2]
I only find many html files and some FormulaStats and filecounts files in dataset. But no file is called 'query' and I couldn't find anything about query in CorpusOverview.md. Could anyone help me? any help would be appreciated!

**Comment by moonlightlane** [comment]
I had the same issue today; I think it is here: https://www.nii.ac.jp/dsc/idr/en/ntcir/ntcir-taskdata.html

**Comment by BehroozMansouri** [comment]
I have added a sub-directory, "TestQueries". This includes the 20 concrete and 20 wildcard queries. 
Also note that there was a new lab at CLEF 2020, ARQMath where 45 queries were introduced on the second task, formula retrieval. You might use that dataset as well.
