### ISSUE TITLE
how to use my data to run this model

### ISSUE THREAD

**Issue by Zxiaoma** [BehroozMansouri/TangentCFT#3]
my data is standard latex format and saved it as txt，
just like: g(x,y) = \\frac{1}{n^2} \sum_{i=[n/2]}^{n/2} \sum_{j=[n/2]}^{n/2} f(x+i,x+j)
how to extract the formulas become a tuples？

**Comment by Zxiaoma** [comment]
i found the "LatexToMathML.convert_to_mathml" function raise some problem："Error in converting LaTeX to MathML: ..."

**Comment by BehroozMansouri** [comment]
Can you please provide the complete error and stack trace?
Also, the version of latexml that you are using? The latest version of latexml has a very low failure rate in conversion. One possible way to check if the extraction is failing is to directly use the command line for extraction.

**Comment by Zxiaoma** [comment]
OK，i just try to test my data,  which just one line "g(x,y) = \frac{1}{n^2} \sum_{i=[n/2]}^{n/2} \sum_{j=[n/2]}^{n/2} f(x+i,x+j)" in a.txt file. And then i choose the mse_data_reader, to parser the formulas.  But the console print the errors 
"Error in converting LaTeX to MathML: g(x,y) = \frac{1}{n^2} \sum_{i=[n/2]}^{n/2} \sum_{j=[n/2]}^{n/2} f(x+i,x+j)”
the version is the latest

**Comment by Zxiaoma** [comment]
Can i just use the python module  "latex2mathml.converter" to replace the "mws.sty.ltxml" ?

**Comment by BehroozMansouri** [comment]
Have you tried directly calling the TangentS Tuple_Extraction.py and call the method "latex_math_to_slt_tuples"?

**Comment by Zxiaoma** [comment]
yes,  i had tried your method,  but still found the problem.
Sorry to have bothered you, i  will try other methods. Thank you~

**Comment by voxdzung** [comment]
Hi @Zxiaoma, have you converted your query yet ? I have the same problem and I don't know how to fix it.

**Comment by jainatharva21** [comment]
I was able to convert my query using the latex_math_to_slt_tuples, how do I go about creating the slt_ret.tsv file for my particular tuple that I created @BehroozMansouri @zanibbi @ARQMath

**Comment by BehroozMansouri** [comment]
@jainatharva21 Depending on if you have trained the model or not, you can use "tangent_cft_front_end" module, and set the train parameter to False/True. Line 65 is the retrieval method and line 69 is for saving the results.
