### ISSUE TITLE
[LaTeX input] Raised .get_query() error from AbstractDataReader class

### ISSUE THREAD

**Issue by norbertstrzelecki** [BehroozMansouri/TangentCFT#9]
Hi, thanks for a very interesting concept and the codebase to try it out.

I try to run the code with the command:
```bash
python3 tangent_cft_front_end.py -ds "Dataset/latex_samples.csv" --wiki False -cid 1 -em slt_encoder.tsv --mp slt_model --rf slt_ret.tsv --ri 1
```
using a LaTeX input (`latex_samples.csv`) as follows:
```csv
\frac12$$01
\frac{3}{2}$$02
\frac{1}{2\pi}\int_{-\infty}^{\infty}e^{-\frac{x^2}{2}}dx$$03
\frac{5}{6}x-\frac{4}{3}y+\frac{5}{4}z={8}$$04
\sqrt{x^2+1}$$05
```

Unfortunately, I'm receiving that error:
```bash
reading train data...
Convert LaTeX to MathML:$\frac12$
Convert LaTeX to MathML:$\frac{3}{2}$
Convert LaTeX to MathML:$\frac{1}{2\pi}\int_{-\infty}^{\infty}e^{-\frac{x^2}{2}}dx$
Convert LaTeX to MathML:$\frac{5}{6}x-\frac{4}{3}y+\frac{5}{4}z={8}$
Convert LaTeX to MathML:$\sqrt{x^2+1}$
0
5
encoding train data...
training the fast text model...
Setting Configuration
Training the model
saving the fast text model...

Traceback (most recent call last):
  File "tangent_cft_front_end.py", line 93, in <module>
    main()
  File "tangent_cft_front_end.py", line 72, in main
    tokenize_number
  File "/TangentCFT/tangent_cft_back_end.py", line 70, in retrieval
    dictionary_query_tuples = self.data_reader.get_query()
  File "/TangentCFT/DataReader/abstract_data_reader.py", line 6, in get_query
    raise NotImplementedError
NotImplementedError
``` 

I also got rid of the missing argument issue in that class:
```
class AbstractDataReader:
(...)
    def get_query(self):
        raise NotImplementedError
```
because of the line `dictionary_query_tuples = self.data_reader.get_query()` in the `/TangentCFT/tangent_cft_back_end.py`.

Do I understand it correctly that `.csv` input uses the `MSEDataReader` class, and that there is not implemented `.get_query()` method in that class and that's why the error occurs? The error, of course, is not showing when `--r False` flag is set (no retrieval, so no get query method needed), but I'm not sure if that's the case and maybe I'm missing the point of the whole csv data usage.

Could you please shed a light on the LaTeX formulas (in .csv) usage with your code? Thank you!

**Comment by voxdzung** [comment]
Hi @norbertstrzelecki, I have the same problem with you. Could you tell me how to fix the error please ?
